### PR TITLE
Improve ssh defaults and support per-server usernames

### PR DESCRIPTION
**Pull request by singlethink**

### CODE REVIEW

**Comment by bilby91** [comment]
Any plan for merging this ?

**Comment by rjocoleman** [comment]
egad, I didn't a notification of the last commit!

**Comment by rjocoleman** [comment]
sorry for the extreme delay - thanks @singlethink and @bilby91, I bumped to v0.2.0 and pushed the release.

**Comment by bilby91** [comment]
@rjocoleman Awesome!

**Pull request merged**
